countryNames = {
'ad' : {'name' : 'Andorra','code' : '+376'},
'ae' : {'name' : 'United Arab Emirates','code' : '+971'},
'af' : {'name' : 'Afghanistan','code' : '+93'},
'ag' : {'name' : 'Antigua and Barbuda','code' : '+1268'},
'ai' : {'name' : 'Anguilla','code' : '+1264'},
'al' : {'name' : 'Albania','code' : '+355'},
'am' : {'name' : 'Armenia','code' : '+374'},
'ao' : {'name' : 'Angola','code' : '+244'},
'ar' : {'name' : 'Argentina','code' : '+54'},
'as' : {'name' : 'American Samoa','code' : '+1684'},
'at' : {'name' : 'Austria','code' : '+43'},
'au' : {'name' : 'Australia','code' : '+61'},
'aw' : {'name' : 'Aruba','code' : '+297'},
'ax' : {'name' : 'Åland Islands','code' : '+358'},
'az' : {'name' : 'Azerbaijan','code' : '+994'},
'ba' : {'name' : 'Bosnia and Herzegovina','code' : '+387'},
'bb' : {'name' : 'Barbados','code' : '+1246'},
'bd' : {'name' : 'Bangladesh','code' : '+880'},
'be' : {'name' : 'Belgium','code' : '+32'},
'bf' : {'name' : 'Burkina Faso','code' : '+226'},
'bg' : {'name' : 'Bulgaria','code' : '+359'},
'bh' : {'name' : 'Bahrain','code' : '+973'},
'bi' : {'name' : 'Burundi','code' : '+257'},
'bj' : {'name' : 'Benin','code' : '+229'},
'bl' : {'name' : 'Saint Barthélemy','code' : '+590'},
'bm' : {'name' : 'Bermuda','code' : '+1441'},
'bn' : {'name' : 'Brunei Darussalam','code' : '+673'},
'bo' : {'name' : 'Bolivia','code' : '+591'},
'bq' : {'name' : 'Bonaire, Sint Eustatius and Saba','code' : '+5997'},
'br' : {'name' : 'Brazil','code' : '+55'},
'bs' : {'name' : 'Bahamas','code' : '+1242'},
'bt' : {'name' : 'Bhutan','code' : '+975'},
'bw' : {'name' : 'Botswana','code' : '+267'},
'by' : {'name' : 'Belarus','code' : '+375'},
'bz' : {'name' : 'Belize','code' : '+501'},
'ca' : {'name' : 'Canada','code' : '+1'},
'cc' : {'name' : 'Cocos (Keeling) Islands','code' : '+61891'},
'cd' : {'name' : 'Congo (Democratic Republic)','code' : '+243'},
'cf' : {'name' : 'Central African Republic','code' : '+236'},
'cg' : {'name' : 'Congo (Republic)','code' : '+242'},
'ch' : {'name' : 'Switzerland','code' : '+41'},
'ci' : {'name' : 'Côte d’Ivoire','code' : '+225'},
'ck' : {'name' : 'Cook Islands','code' : '+682'},
'cl' : {'name' : 'Chile','code' : '+56'},
'cm' : {'name' : 'Cameroon','code' : '+237'},
'cn' : {'name' : 'China','code' : '+86'},
'co' : {'name' : 'Colombia','code' : '+57'},
'cr' : {'name' : 'Costa Rica','code' : '+506'},
'cu' : {'name' : 'Cuba','code' : '+53'},
'cv' : {'name' : 'Cabo Verde','code' : '+238'},
'cw' : {'name' : 'Curaçao','code' : '+5999'},
'cx' : {'name' : 'Christmas Island','code' : '+61891'},
'cy' : {'name' : 'Cyprus','code' : '+357'},
'cz' : {'name' : 'Czech Republic','code' : '+420'},
'de' : {'name' : 'Germany','code' : '+49'},
'dj' : {'name' : 'Djibouti','code' : '+253'},
'dk' : {'name' : 'Denmark','code' : '+45'},
'dm' : {'name' : 'Dominica','code' : '+1767'},
'do' : {'name' : 'Dominican Republic','code' : '+1809'},
'dz' : {'name' : 'Algeria','code' : '+213'},
'ec' : {'name' : 'Ecuador','code' : '+593'},
'ee' : {'name' : 'Estonia','code' : '+372'},
'eg' : {'name' : 'Egypt','code' : '+20'},
'eh' : {'name' : 'Western Sahara','code' : '+212'},
'er' : {'name' : 'Eritrea','code' : '+291'},
'es' : {'name' : 'Spain','code' : '+34'},
'et' : {'name' : 'Ethiopia','code' : '+251'},
'fi' : {'name' : 'Finland','code' : '+358'},
'fj' : {'name' : 'Fiji','code' : '+679'},
'fk' : {'name' : 'Falkland Islands (Malvinas)','code' : '+500'},
'fm' : {'name' : 'Micronesia (Federated States of)','code' : '+691'},
'fo' : {'name' : 'Faroe Islands','code' : '+298'},
'fr' : {'name' : 'France','code' : '+33'},
'ga' : {'name' : 'Gabon','code' : '+241'},
'gb-eng' : {'name' : 'England','code' : '+44'},
'gb-nir' : {'name' : 'Northern Ireland','code' : '+44'},
'gb' : {'name' : 'United Kingdom','code' : '+44'},
'gb-sct' : {'name' : 'Scotland','code' : '+44'},
'gb-wls' : {'name' : 'Wales','code' : '+44'},
'gd' : {'name' : 'Grenada','code' : '+1473'},
'ge' : {'name' : 'Georgia','code' : '+995'},
'gf' : {'name' : 'French Guiana','code' : '+594'},
'gg' : {'name' : 'Guernsey','code' : '+441481'},
'gh' : {'name' : 'Ghana','code' : '+233'},
'gi' : {'name' : 'Gibraltar','code' : '+350'},
'gl' : {'name' : 'Greenland','code' : '+299'},
'gm' : {'name' : 'Gambia','code' : '+220'},
'gn' : {'name' : 'Guinea','code' : '+224'},
'gp' : {'name' : 'Guadeloupe','code' : '+590'},
'gq' : {'name' : 'Equatorial Guinea','code' : '+240'},
'gr' : {'name' : 'Greece','code' : '+30'},
'gt' : {'name' : 'Guatemala','code' : '+502'},
'gu' : {'name' : 'Guam','code' : '+1671'},
'gw' : {'name' : 'Guinea-Bissau','code' : '+245'},
'gy' : {'name' : 'Guyana','code' : '+592'},
'hk' : {'name' : 'Hong Kong','code' : '+852'},
'hn' : {'name' : 'Honduras','code' : '+504'},
'hr' : {'name' : 'Croatia','code' : '+385'},
'ht' : {'name' : 'Haiti','code' : '+509'},
'hu' : {'name' : 'Hungary','code' : '+36'},
'id' : {'name' : 'Indonesia','code' : '+62'},
'ie' : {'name' : 'Ireland','code' : '+353'},
'il' : {'name' : 'Israel','code' : '+972'},
'im' : {'name' : 'Isle of Man','code' : '+441624'},
'in' : {'name' : 'India','code' : '+91'},
'io' : {'name' : 'British Indian Ocean Territory','code' : '+246'},
'iq' : {'name' : 'Iraq','code' : '+964'},
'ir' : {'name' : 'Iran','code' : '+98'},
'is' : {'name' : 'Iceland','code' : '+354'},
'it' : {'name' : 'Italy','code' : '+39'},
'je' : {'name' : 'Jersey','code' : '+441534'},
'jm' : {'name' : 'Jamaica','code' : '+1876'},
'jo' : {'name' : 'Jordan','code' : '+962'},
'jp' : {'name' : 'Japan','code' : '+81'},
'ke' : {'name' : 'Kenya','code' : '+254'},
'kg' : {'name' : 'Kyrgyzstan','code' : '+996'},
'kh' : {'name' : 'Cambodia','code' : '+855'},
'ki' : {'name' : 'Kiribati','code' : '+686'},
'km' : {'name' : 'Comoros','code' : '+269'},
'kn' : {'name' : 'Saint Kitts and Nevis','code' : '+1869'},
'kp' : {'name' : 'Korea (Democratic People’s Republic – North Korea)','code' : '+850'},
'kr' : {'name' : 'South Korea','code' : '+82'},
'kw' : {'name' : 'Kuwait','code' : '+965'},
'ky' : {'name' : 'Cayman Islands','code' : '+1345'},
'kz' : {'name' : 'Kazakhstan','code' : '+7'},
'la' : {'name' : 'Lao People’s Democratic Republic','code' : '+856'},
'lb' : {'name' : 'Lebanon','code' : '+961'},
'lc' : {'name' : 'Saint Lucia','code' : '+1758'},
'li' : {'name' : 'Liechtenstein','code' : '+423'},
'lk' : {'name' : 'Sri Lanka','code' : '+94'},
'lr' : {'name' : 'Liberia','code' : '+231'},
'ls' : {'name' : 'Lesotho','code' : '+266'},
'lt' : {'name' : 'Lithuania','code' : '+370'},
'lu' : {'name' : 'Luxembourg','code' : '+352'},
'lv' : {'name' : 'Latvia','code' : '+371'},
'ly' : {'name' : 'Libya','code' : '+218'},
'ma' : {'name' : 'Morocco','code' : '+212'},
'mc' : {'name' : 'Monaco','code' : '+377'},
'md' : {'name' : 'Moldova (Republic of)','code' : '+373'},
'me' : {'name' : 'Montenegro','code' : '+382'},
'mf' : {'name' : 'Saint Martin (French part)','code' : '+590'},
'mg' : {'name' : 'Madagascar','code' : '+261'},
'mh' : {'name' : 'Marshall Islands','code' : '+692'},
'mk' : {'name' : 'North Macedonia','code' : '+389'},
'ml' : {'name' : 'Mali','code' : '+223'},
'mm' : {'name' : 'Myanmar','code' : '+95'},
'mn' : {'name' : 'Mongolia','code' : '+976'},
'mo' : {'name' : 'Macao','code' : '+853'},
'mp' : {'name' : 'Northern Mariana Islands','code' : '+1670'},
'mq' : {'name' : 'Martinique','code' : '+596'},
'mr' : {'name' : 'Mauritania','code' : '+222'},
'ms' : {'name' : 'Montserrat','code' : '+1664'},
'mt' : {'name' : 'Malta','code' : '+356'},
'mu' : {'name' : 'Mauritius','code' : '+230'},
'mv' : {'name' : 'Maldives','code' : '+960'},
'mw' : {'name' : 'Malawi','code' : '+265'},
'mx' : {'name' : 'Mexico','code' : '+52'},
'my' : {'name' : 'Malaysia','code' : '+60'},
'mz' : {'name' : 'Mozambique','code' : '+258'},
'na' : {'name' : 'Namibia','code' : '+264'},
'nc' : {'name' : 'New Caledonia','code' : '+687'},
'ne' : {'name' : 'Niger','code' : '+227'},
'nf' : {'name' : 'Norfolk Island','code' : '+672'},
'ng' : {'name' : 'Nigeria','code' : '+234'},
'ni' : {'name' : 'Nicaragua','code' : '+505'},
'nl' : {'name' : 'Netherlands','code' : '+31'},
'no' : {'name' : 'Norway','code' : '+47'},
'np' : {'name' : 'Nepal','code' : '+977'},
'nr' : {'name' : 'Nauru','code' : '+674'},
'nu' : {'name' : 'Niue','code' : '+683'},
'nz' : {'name' : 'New Zealand','code' : '+64'},
'om' : {'name' : 'Oman','code' : '+968'},
'pa' : {'name' : 'Panama','code' : '+507'},
'pe' : {'name' : 'Peru','code' : '+51'},
'pf' : {'name' : 'French Polynesia','code' : '+689'},
'pg' : {'name' : 'Papua New Guinea','code' : '+675'},
'ph' : {'name' : 'Philippines','code' : '+63'},
'pk' : {'name' : 'Pakistan','code' : '+92'},
'pl' : {'name' : 'Poland','code' : '+48'},
'pm' : {'name' : 'Saint Pierre and Miquelon','code' : '+508'},
'pn' : {'name' : 'Pitcairn Islands','code' : '+64'},
'pr' : {'name' : 'Puerto Rico','code' : '+1787'},
'ps' : {'name' : 'Palestine, State of','code' : '+970'},
'pt' : {'name' : 'Portugal','code' : '+351'},
'pw' : {'name' : 'Palau','code' : '+680'},
'py' : {'name' : 'Paraguay','code' : '+595'},
'qa' : {'name' : 'Qatar','code' : '+974'},
're' : {'name' : 'Réunion','code' : '+262'},
'ro' : {'name' : 'Romania','code' : '+40'},
'rs' : {'name' : 'Serbia','code' : '+381'},
'ru' : {'name' : 'Russia','code' : '+7'},
'rw' : {'name' : 'Rwanda','code' : '+250'},
'sa' : {'name' : 'Saudi Arabia','code' : '+966'},
'sb' : {'name' : 'Solomon Islands','code' : '+677'},
'sc' : {'name' : 'Seychelles','code' : '+248'},
'sd' : {'name' : 'Sudan','code' : '+249'},
'se' : {'name' : 'Sweden','code' : '+46'},
'sg' : {'name' : 'Singapore','code' : '+65'},
'sh' : {'name' : 'Saint Helena, Ascension and Tristan da Cunha','code' : '+290'},
'si' : {'name' : 'Slovenia','code' : '+386'},
'sj' : {'name' : 'Svalbard and Jan Mayen','code' : '+47'},
'sk' : {'name' : 'Slovakia','code' : '+421'},
'sl' : {'name' : 'Sierra Leone','code' : '+232'},
'sm' : {'name' : 'San Marino','code' : '+378'},
'sn' : {'name' : 'Senegal','code' : '+221'},
'so' : {'name' : 'Somalia','code' : '+252'},
'sr' : {'name' : 'Suriname','code' : '+597'},
'ss' : {'name' : 'South Sudan','code' : '+211'},
'st' : {'name' : 'São Tomé and Príncipe','code' : '+239'},
'sv' : {'name' : 'El Salvador','code' : '+503'},
'sx' : {'name' : 'Sint Maarten (Dutch part)','code' : '+1721'},
'sy' : {'name' : 'Syrian Arab Republic','code' : '+963'},
'sz' : {'name' : 'Eswatini (Swaziland)','code' : '+268'},
'tc' : {'name' : 'Turks and Caicos Islands','code' : '+1649'},
'td' : {'name' : 'Chad','code' : '+235'},
'tg' : {'name' : 'Togo','code' : '+228'},
'th' : {'name' : 'Thailand','code' : '+66'},
'tj' : {'name' : 'Tajikistan','code' : '+992'},
'tk' : {'name' : 'Tokelau','code' : '+690'},
'tl' : {'name' : 'Timor-Leste','code' : '+670'},
'tm' : {'name' : 'Turkmenistan','code' : '+993'},
'tn' : {'name' : 'Tunisia','code' : '+216'},
'to' : {'name' : 'Tonga','code' : '+676'},
'tr' : {'name' : 'Türkiye','code' : '+90'},
'tt' : {'name' : 'Trinidad and Tobago','code' : '+1868'},
'tv' : {'name' : 'Tuvalu','code' : '+688'},
'tw' : {'name' : 'Taiwan','code' : '+886'},
'tz' : {'name' : 'Tanzania','code' : '+255'},
'ua' : {'name' : 'Ukraine','code' : '+380'},
'ug' : {'name' : 'Uganda','code' : '+256'},
'um' : {'name' : 'United States Minor Outlying Islands','code' : '+1'},
'us' : {'name' : 'United States','code' : '+1'},
'uy' : {'name' : 'Uruguay','code' : '+598'},
'uz' : {'name' : 'Uzbekistan','code' : '+998'},
'va' : {'name' : 'Holy See (Vatican City State)','code' : '+379'},
'vc' : {'name' : 'Saint Vincent and the Grenadines','code' : '+1784'},
've' : {'name' : 'Venezuela (Bolivarian Republic of)','code' : '+58'},
'vg' : {'name' : 'Virgin Islands (British)','code' : '+1284'},
'vi' : {'name' : 'Virgin Islands (U.S.)','code' : '+1340'},
'vn' : {'name' : 'Vietnam','code' : '+84'},
'vu' : {'name' : 'Vanuatu','code' : '+678'},
'wf' : {'name' : 'Wallis and Futuna','code' : '+681'},
'ws' : {'name' : 'Samoa','code' : '+685'},
'xk' : {'name' : 'Kosovo','code' : '+383'},
'ye' : {'name' : 'Yemen','code' : '+967'},
'yt' : {'name' : 'Mayotte','code' : '+262'},
'za' : {'name' : 'South Africa','code' : '+27'},
'zm' : {'name' : 'Zambia','code' : '+260'},
'zw' : {'name' : 'Zimbabwe','code' : '+263'}};

