NO_ENTRY_POINT = 404
INVALID_CREDENTIALS = 469
NOT_AUTHORIZED = 401
INVALID_JSON = 400
MISSING_DATA = 400
BAD_REQUEST = 400
COULD_BE_BOT = 911
INTERNAL_ERROR = 413
ID_UPDATE_FAILURE = 317
BAD_GATEWAY = 502
UNSUPPORTED_MEDIA = 415
CONFLICT = 409
INTERNAL_SERVER_ERROR = 500

__all__ = [
    "INVALID_CREDENTIALS",
    "NOT_AUTHORIZED",
    "INVALID_JSON",
    "MISSING_DATA",
    "COULD_BE_BOT",
    "INTERNAL_ERROR",
    "NO_ENTRY_POINT",
    "ID_UPDATE_FAILURE",
    "BAD_GATEWAY",
    "BAD_REQUEST",
    "UNSUPPORTED_MEDIA",
    "CONFLICT",
    "INTERNAL_SERVER_ERROR"
]
